# Init a github repo

name: Init a repo with a new main branch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repotarget:
        description: name of the repo to git init + create main branch
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout remote repo to git init
        uses: actions/checkout@v3
        with:
          repository: vinywood/${{ inputs.repotarget }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      
      #- name: Check if main branch exists
      #  run: git ls-remote --exit-code --heads origin main
        
      # Runs a single command using the runners shell
      - id: mainbranch
        if: ${{ failure() }}
        run: |
          echo Hello, branch main is not there!
          echo "{exis}={false}" >> $GITHUB_OUTPUT
      
      # Runs a test
      - name: Run a test
        if: ${{ steps.mainbranch.outputs.exis }} == "false" 
        run: echo Main branch n existe pas

      - name: Add remote Git repository
        if: ${{ steps.mainbranch.outputs.exis }} == "false" 
        run: echo Main branch n existe pas https://github.com/vinywood/${{ inputs.repotarget }}

      - name: Git add and push
        if: ${{ steps.mainbranch.outputs.exis }} == false
        run: echo Main branch n existe pas https://github.com/vinywood/${{ inputs.repotarget }}
    
      
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
