# This is a basic workflow to help you get started with Actions

name: Test Hello World

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test1=hello" >> "$GITHUB_ENV"
      - id: step2
        run: echo "test2=world" >> "$GITHUB_ENV"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: env.test1
          OUTPUT2: env.test2
        run: echo "$OUTPUT1 $OUTPUT2"
       
      - name: Run a test  
        if:  env.OUTPUT1 = hello 
        run: echo if est bien egale
