# This is a basic workflow to help you get started with Actions

name: Test Hello World

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test}}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
        
      - name: afficher
        run: echo ${{ outputs.output1 }} ${{ outputs.output2 }}
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
       
      - name: Run a test  
        run: |
          if [ "$OUTPUT1" == "hello" ]; then 
             echo "OUTPUT1 est bien hello"
          else
            echo "OUTPUT1 n est pas  hello"
          fi
