# This is a basic workflow to help you get started with Actions

name: Test Hello World

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test}}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
        
      - name: afficher
        run: echo ${{ needs.job1.outputs.output1 }} ${{ needs.job1.outputs.output2 }}
        
  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      OUTPUT1: ${{needs.job1.outputs.output1}}
      OUTPUT2: ${{needs.job1.outputs.output2}}
      OUTPUT3: "toto"
      
    steps:
      - name: Print
        run: echo "$OUTPUT1 $OUTPUT2 $OUTPUT3"
       
      - name: Run a test  
        run: |
          if [ "$OUTPUT1" == "hello" ]; then 
             echo "$OUTPUT1 est bien hello"
             echo "$OUTPUT3"
          else
            echo "$OUTPUT1 n est pas  hello"
            echo "$OUTPUT3"
          fi
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: mailx
        run:  |
          RC=$(apt list --installed  |grep -i mailx|grep installed |wc -l)
          if [ $RC -eq 0 ]; then
            echo mailx  not installed
            echo
            sudo apt-get update
            echo
            echo "--> Install mailx"
            sudo apt-get install -y bsd-mailx 
            echo
            echo "--> restart mailx"
            sudo service postfix restart
            
            #echo "relay_domains = airfrance.fr, klm.com" >> /etc/postfix/main.cf
            #echo "transport_maps = hash:/etc/postfix/transport" >> /etc/postfix/main.cf
            #echo "klm.com  smtp:[mailgate1.klm.com]" >> /etc/postfix/transport
            #echo "airfrance.fr  smtp:[mailsmtp.airfrance.fr]" >> /etc/postfix/transport
            
            echo "<html><b>Hello</b></html>" | mailx -a "Content-type: text/html;" -s "Testing" -r "PT<container@gmail.com>"  chanh@gmail.com -c vinguyen@airfrance.Fr
            
          fi 
      - name: send mailx
        run:  echo "<html><b>Hello</b></html>" | mailx -a "Content-type: text/html;" -s "Testing" -r "PT<container@gmail.com>"  chanh.ng@gmail.com -c vinguyen@airfrance.Fr
          
